#!/usr/bin/env python3
"""
build_sections.py
Re-generates dist/js/sections-data.js from dist/sections/*.html
Run this after editing any section file:
    python3 build_sections.py
"""
import json, os

DIST = os.path.join(os.path.dirname(__file__), 'dist')
SECTIONS_DIR = os.path.join(DIST, 'sections')
OUT_FILE = os.path.join(DIST, 'js', 'sections-data.js')

SECTIONS = [
    's1-overview',
    's2-pipeline',
    's3-theory',
    's4-subjects',
    's5-foreign',
    's6-cluster',
    's7-hypothesis',
    's8-corr',
]

lines = [
    '/**\n',
    ' * sections-data.js – Inlined HTML partials (no fetch / server required)\n',
    ' * AUTO-GENERATED by build_sections.py — do not edit manually.\n',
    ' */\n',
    'window.__SECTIONS = {\n',
]

for name in SECTIONS:
    path = os.path.join(SECTIONS_DIR, name + '.html')
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read().rstrip('\n')
    lines.append(f'  {json.dumps(name)}: {json.dumps(content)},\n')

lines.append('};\n')

with open(OUT_FILE, 'w', encoding='utf-8') as f:
    f.writelines(lines)

kb = os.path.getsize(OUT_FILE) / 1024
print(f'✅  {OUT_FILE}  ({kb:.1f} KB)')
